// swift-tools-version:5.1
//  The swift-tools-version declares the minimum version of Swift required to build this package.
//
// --------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// --------------------------------------------------------------------------

import PackageDescription

let package = Package(
    name: "AzureMapsSearch",
    platforms: [
        .macOS(.v10_15), .iOS(.v12), .tvOS(.v12)
    ],
    products: [
        .library(name: "AzureMapsSearch", type: .static, targets: ["AzureMapsSearch"])
    ],
    dependencies: [
        .package(
            url: "https://github.com/Azure/SwiftPM-AzureCore.git",
            .branch("dev/AzureCore")
        )
    ],
    targets: [
        // Build targets
        .target(
            name: "AzureMapsSearch",
            dependencies: ["AzureCore"],
            path: "Source"
        ),
        .testTarget(
            name: "AzureMapsSearchTests",
            dependencies: [
                "AzureMapsSearch",
            ],
            path: "Tests",
            exclude: []
        )
    ],
    swiftLanguageVersions: [.v5]
)
